openapi: 3.0.0
info:
    version: '1.0'


paths:
    /b2b/v1/front/products/list:
        post:
            summary: Get products list
            parameters:
              - $ref: '../definitions.yaml#/components/parameters/AuthorizationHeader'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ProductsListRequest'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProductsListResponse'
                '404':
                    description: Products not found
                    content:
                        application/json:
                            schema:
                                $ref: '../definitions.yaml#/components/schemas/ResponseBodyError'

components:
    schemas:
        ProductsListRequest:
            description: Products list request.
            type: object
            additionalProperties: false
            required:
              - category_id
            properties:
                locale:
                    $ref: '../definitions.yaml#/components/schemas/Localization'
                store_id:
                    description: Store ID
                    $ref: '../definitions.yaml#/components/schemas/StoreId'
                category_id:
                    type: string
                page_token:
                    description: A token identifying the first item to receive (use value of next_page_token from previous response). Can be omitted to start from the very beginning.
                    type: string
                limit:
                    description: Limits the number of items in the response to this
                        value.
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 100

        ProductsListResponse:
            description: Products list response.
            type: object
            additionalProperties: false
            required:
              - products
            properties:
                next_page_token:
                    description: A token for fetching the next page of results. Pass this value in the subsequent request to retrieve the next set of items. If absent from the response, it indicates the last page has been reached.
                    type: string
                products:
                    description: Products
                    type: array
                    items:
                        $ref: '#/components/schemas/Product'
        Product:
            description: Product
            type: object
            additionalProperties: false
            required:
              - id
              - title
              - price
              - image_url
            properties:
                id:
                    description: Product ID
                    type: string
                title:
                    description: Product title
                    type: string
                price:
                    description: Product price
                    $ref: '../definitions.yaml#/components/schemas/Numeric'
                image_url:
                    description: Image URL
                    type: string
